local Stopwatch = require('split-second-stopwatch')

describe('split-second-stopwatch', function()
  it('new stopwatch starts in ready state', function()
    local stopwatch = Stopwatch:new()
    assert.are.same('ready', stopwatch:state())
  end)

  it("new stopwatch's current lap has no elapsed time", function()
    local stopwatch = Stopwatch:new()
    assert.are.same('00:00:00', stopwatch:current_lap())
  end)

  it("new stopwatch's total has no elapsed time", function()
    local stopwatch = Stopwatch:new()
    assert.are.same('00:00:00', stopwatch:total())
  end)

  it('new stopwatch does not have previous laps', function()
    local stopwatch = Stopwatch:new()
    assert.are.same({}, stopwatch:previous_laps())
  end)

  it('start from ready state changes state to running', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    assert.are.same('running', stopwatch:state())
  end)

  it('start does not change previous laps', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    assert.are.same({}, stopwatch:previous_laps())
  end)

  it('start initiates time tracking for current lap', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:00:05')
    assert.are.same('00:00:05', stopwatch:current_lap())
  end)

  it('start initiates time tracking for total', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:00:23')
    assert.are.same('00:00:23', stopwatch:total())
  end)

  it('start cannot be called from running state', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    assert.has_error(function()
      stopwatch:start()
    end, 'cannot start an already running stopwatch')
  end)

  it('stop from running state changes state to stopped', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:stop()
    assert.are.same('stopped', stopwatch:state())
  end)

  it('stop pauses time tracking for current lap', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:00:05')
    stopwatch:stop()
    stopwatch:advance_time('00:00:08')
    assert.are.same('00:00:05', stopwatch:current_lap())
  end)

  it('stop pauses time tracking for total', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:00:13')
    stopwatch:stop()
    stopwatch:advance_time('00:00:44')
    assert.are.same('00:00:13', stopwatch:total())
  end)

  it('stop cannot be called from ready state', function()
    local stopwatch = Stopwatch:new()
    assert.has_error(function()
      stopwatch:stop()
    end, 'cannot stop a stopwatch that is not running')
  end)

  it('stop cannot be called from stopped state', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:stop()
    assert.has_error(function()
      stopwatch:stop()
    end, 'cannot stop a stopwatch that is not running')
  end)

  it('start from stopped state changes state to running', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:stop()
    stopwatch:start()
    assert.are.same('running', stopwatch:state())
  end)

  it('start from stopped state resumes time tracking for current lap', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:01:20')
    stopwatch:stop()
    stopwatch:advance_time('00:00:20')
    stopwatch:start()
    stopwatch:advance_time('00:00:08')
    assert.are.same('00:01:28', stopwatch:current_lap())
  end)

  it('start from stopped state resumes time tracking for total', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:00:23')
    stopwatch:stop()
    stopwatch:advance_time('00:00:44')
    stopwatch:start()
    stopwatch:advance_time('00:00:09')
    assert.are.same('00:00:32', stopwatch:total())
  end)

  it('lap adds current lap to previous laps', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:01:38')
    stopwatch:lap()
    assert.are.same({ '00:01:38' }, stopwatch:previous_laps())
    stopwatch:advance_time('00:00:44')
    stopwatch:lap()
    assert.are.same({ '00:01:38', '00:00:44' }, stopwatch:previous_laps())
  end)

  it('lap resets current lap and resumes time tracking', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:08:22')
    stopwatch:lap()
    assert.are.same('00:00:00', stopwatch:current_lap())
    stopwatch:advance_time('00:00:15')
    assert.are.same('00:00:15', stopwatch:current_lap())
  end)

  it('lap continues time tracking for total', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:00:22')
    stopwatch:lap()
    stopwatch:advance_time('00:00:33')
    assert.are.same('00:00:55', stopwatch:total())
  end)

  it('lap cannot be called from ready state', function()
    local stopwatch = Stopwatch:new()
    assert.has_error(function()
      stopwatch:lap()
    end, 'cannot lap a stopwatch that is not running')
  end)

  it('lap cannot be called from stopped state', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:stop()
    assert.has_error(function()
      stopwatch:lap()
    end, 'cannot lap a stopwatch that is not running')
  end)

  it('stop does not change previous laps', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:11:22')
    stopwatch:lap()
    assert.are.same({ '00:11:22' }, stopwatch:previous_laps())
    stopwatch:stop()
    assert.are.same({ '00:11:22' }, stopwatch:previous_laps())
  end)

  it('reset from stopped state changes state to ready', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:stop()
    stopwatch:reset()
    assert.are.same('ready', stopwatch:state())
  end)

  it('reset resets current lap', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:00:10')
    stopwatch:stop()
    stopwatch:reset()
    assert.are.same('00:00:00', stopwatch:current_lap())
  end)

  it('reset clears previous laps', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('00:00:10')
    stopwatch:lap()
    stopwatch:advance_time('00:00:20')
    stopwatch:lap()
    assert.are.same({ '00:00:10', '00:00:20' }, stopwatch:previous_laps())
    stopwatch:stop()
    stopwatch:reset()
    assert.are.same({}, stopwatch:previous_laps())
  end)

  it('reset cannot be called from ready state', function()
    local stopwatch = Stopwatch:new()
    assert.has_error(function()
      stopwatch:reset()
    end, 'cannot reset a stopwatch that is not stopped')
  end)

  it('reset cannot be called from running state', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    assert.has_error(function()
      stopwatch:reset()
    end, 'cannot reset a stopwatch that is not stopped')
  end)

  it('supports very long laps', function()
    local stopwatch = Stopwatch:new()
    stopwatch:start()
    stopwatch:advance_time('01:23:45')
    assert.are.same('01:23:45', stopwatch:current_lap())
    stopwatch:lap()
    assert.are.same({ '01:23:45' }, stopwatch:previous_laps())
    stopwatch:advance_time('04:01:40')
    assert.are.same('04:01:40', stopwatch:current_lap())
    assert.are.same('05:25:25', stopwatch:total())
    stopwatch:lap()
    assert.are.same({ '01:23:45', '04:01:40' }, stopwatch:previous_laps())
    stopwatch:advance_time('08:43:05')
    assert.are.same('08:43:05', stopwatch:current_lap())
    assert.are.same('14:08:30', stopwatch:total())
    stopwatch:lap()
    assert.are.same({ '01:23:45', '04:01:40', '08:43:05' }, stopwatch:previous_laps())
  end)
end)
