local phone_number = require('phone-number')

describe('phone-number', function()
  it('cleans the number', function()
    assert.are.equal('2234567890', phone_number.clean('(223) 456-7890'))
  end)

  it('cleans numbers with dots', function()
    assert.are.equal('2234567890', phone_number.clean('223.456.7890'))
  end)

  it('cleans numbers with multiple spaces', function()
    assert.are.equal('2234567890', phone_number.clean('223 456   7890   '))
  end)

  it('invalid when 9 digits', function()
    assert.has_error(function()
      phone_number.clean('123456789')
    end)
  end)

  it('invalid when 11 digits does not start with a 1', function()
    assert.has_error(function()
      phone_number.clean('22234567890')
    end)
  end)

  it('valid when 11 digits and starting with 1', function()
    assert.are.equal('2234567890', phone_number.clean('12234567890'))
  end)

  it('valid when 11 digits and starting with 1 even with punctuation', function()
    assert.are.equal('2234567890', phone_number.clean('+1 (223) 456-7890'))
  end)

  it('invalid when more than 11 digits', function()
    assert.has_error(function()
      phone_number.clean('321234567890')
    end)
  end)

  it('invalid with letters', function()
    assert.has_error(function()
      phone_number.clean('523-abc-7890')
    end)
  end)

  it('invalid with punctuations', function()
    assert.has_error(function()
      phone_number.clean('523-@:!-7890')
    end)
  end)

  it('invalid if area code starts with 0', function()
    assert.has_error(function()
      phone_number.clean('(023) 456-7890')
    end)
  end)

  it('invalid if area code starts with 1', function()
    assert.has_error(function()
      phone_number.clean('(123) 456-7890')
    end)
  end)

  it('invalid if exchange code starts with 0', function()
    assert.has_error(function()
      phone_number.clean('(223) 056-7890')
    end)
  end)

  it('invalid if exchange code starts with 1', function()
    assert.has_error(function()
      phone_number.clean('(223) 156-7890')
    end)
  end)

  it('invalid if area code starts with 0 on valid 11-digit number', function()
    assert.has_error(function()
      phone_number.clean('1 (023) 456-7890')
    end)
  end)

  it('invalid if area code starts with 1 on valid 11-digit number', function()
    assert.has_error(function()
      phone_number.clean('1 (123) 456-7890')
    end)
  end)

  it('invalid if exchange code starts with 0 on valid 11-digit number', function()
    assert.has_error(function()
      phone_number.clean('1 (223) 056-7890')
    end)
  end)

  it('invalid if exchange code starts with 1 on valid 11-digit number', function()
    assert.has_error(function()
      phone_number.clean('1 (223) 156-7890')
    end)
  end)
end)
