local SpaceAge = require('space-age')

describe('space-age', function()
  it('age on earth', function()
    local age = SpaceAge:new(1000000000)
    assert.are.equal(31.69, age.on_earth())
  end)

  it('age on mercury', function()
    local age = SpaceAge:new(2134835688)
    assert.are.equal(280.88, age.on_mercury())
  end)

  it('age on venus', function()
    local age = SpaceAge:new(189839836)
    assert.are.equal(9.78, age.on_venus())
  end)

  it('age on mars', function()
    local age = SpaceAge:new(2129871239)
    assert.are.equal(35.88, age.on_mars())
  end)

  it('age on jupiter', function()
    local age = SpaceAge:new(901876382)
    assert.are.equal(2.41, age.on_jupiter())
  end)

  it('age on saturn', function()
    local age = SpaceAge:new(2000000000)
    assert.are.equal(2.15, age.on_saturn())
  end)

  it('age on uranus', function()
    local age = SpaceAge:new(1210123456)
    assert.are.equal(0.46, age.on_uranus())
  end)

  it('age on neptune', function()
    local age = SpaceAge:new(1821023456)
    assert.are.equal(0.35, age.on_neptune())
  end)

  it('invalid planet causes error', function()
    local age = SpaceAge:new(680804807)
    assert.has_error(function()
      age.on_sun()
    end, 'not a planet')
  end)
end)
