local SpaceAge = require('./space-age')

describe('Space Age', function()
    it('age in seconds', function()
        local age = SpaceAge:new(1000000)
        assert.are.equals(1000000, age.seconds)
    end)

    it('age in earth years', function()
        local age = SpaceAge:new(1000000000)
        assert.are.equals(31.69, age.onEarth())
    end)

    it('age in mercury years', function()
        local age = SpaceAge:new(2134835688)
        assert.are.equals(67.65, age.onEarth())
        assert.are.equals(280.88, age.onMercury())
    end)

    it('age in venus years', function()
        local age = SpaceAge:new(189839836)
        assert.are.equals(6.02, age.onEarth())
        assert.are.equals(9.78, age.onVenus())
    end)

    it('age in mars years', function()
        local age = SpaceAge:new(2329871239)
        assert.are.equals(73.83, age.onEarth())
        assert.are.equals(39.25, age.onMars())
    end)

    it('age in jupiter years', function()
        local age = SpaceAge:new(901876382)
        assert.are.equals(28.58, age.onEarth())
        assert.are.equals(2.41, age.onJupiter())
    end)

    it('age in saturn years', function()
        local age = SpaceAge:new(3000000000)
        assert.are.equals(95.06, age.onEarth())
        assert.are.equals(3.23, age.onSaturn())
    end)

    it('age in uranus years', function()
        local age = SpaceAge:new(3210123456)
        assert.are.equals(101.72, age.onEarth())
        assert.are.equals(1.21, age.onUranus())
    end)

    it('age in neptune year', function()
        local age = SpaceAge:new(8210123456)
        assert.are.equals(260.16, age.onEarth())
        assert.are.equals(1.58, age.onNeptune())
    end)
end)